services:
  # Frontend service - React app
  - type: web
    name: lorcana-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: lorcana-backend
          type: web
          property: host
        sync: false

  # Backend service - Flask API
  - type: web
    name: lorcana-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: lorcana-db
          property: connectionString

# Database - MongoDB
databases:
  - name: lorcana-db
    type: mongodb
    plan: free